_ulid: 01KQB2RE0D0ARARAHS5FKTKMAE
slugs:
  - task-foundation-layout
title: "Foundation: Layout & Navigation"
type: task
spec_ref: "@01KK67BC64PX1P0T8AQG7P1Y1A"
meta_ref: null
plan_ref: null
status: in_progress
blocked_by: []
depends_on: []
context: []
priority: 3
tags: []
vcs_refs: []
history:
  - author: Johan.P
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-05-09T07:22:34.484Z
        previous: null
    command: task-start
    timestamp: 2026-05-09T07:22:34.484Z
created_at: 2026-04-28T22:18:35.405Z
started_at: 2026-05-09T07:22:34.484Z
todos: []
