_ulid: 01KQV5433KZS8E3S7K6ENGKCF0
slugs:
  - task-borg-knowledge-bridge
title: "Implement: Borg Knowledge Bridge"
type: task
spec_ref: "@01KQV53JA9N30W50356Q8K350Q"
derivation: auto
status: in_progress
blocked_by: []
depends_on: []
context: []
priority: 3
tags: []
vcs_refs: []
history:
  - author: Johan.P
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-05-09T07:22:24.592Z
        previous: null
    command: task-start
    timestamp: 2026-05-09T07:22:24.593Z
created_at: 2026-05-05T04:07:45.523Z
started_at: 2026-05-09T07:22:24.592Z
todos: []
