kynetic: "1.0"
project:
  name: Project
  version: 0.1.0
  status: draft
includes:
  - modules/main.yaml
  - modules/terminal.yaml
  - modules/layout.yaml
  - modules/voice.yaml
  - modules/tasks.yaml
  - modules/connectivity.yaml
  - modules/extensions.yaml
