_ulid: 01KPNXFS0NF89NNDQE8Q4P3R27
slugs:
  - task-advanced-workspace-control
title: "Implement: Advanced Workspace Control"
type: task
spec_ref: "@workspace-control"
derivation: auto
status: pending_review
blocked_by: []
depends_on: []
context: []
priority: 3
tags: []
vcs_refs: []
submission_linkage:
  review_url: null
  branch: dispatch/task/task-advanced-workspace-control/01kpnxfs
  captured_at: 2026-04-20T22:31:11.828Z
  commit: 26d8fe46856e5ccd5dbb0797302f622ab95dfffd
  remote: null
  remote_url: null
  upstream_ref: null
history:
  - author: Johan.P
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-04-20T22:25:51.726Z
        previous: null
    command: task-start
    timestamp: 2026-04-20T22:25:51.727Z
  - author: Johan.P
    changes:
      status:
        new: pending_review
        previous: in_progress
      submission_linkage:
        new:
          review_url: null
          branch: dispatch/task/task-advanced-workspace-control/01kpnxfs
          captured_at: 2026-04-20T22:31:11.828Z
          commit: 26d8fe46856e5ccd5dbb0797302f622ab95dfffd
          remote: null
          remote_url: null
          upstream_ref: null
        previous: null
      submitted_at:
        new: 2026-04-20T22:31:11.834Z
        previous: null
    command: task-submit
    timestamp: 2026-04-20T22:31:11.834Z
created_at: 2026-04-20T17:02:25.813Z
started_at: 2026-04-20T22:25:51.726Z
submitted_at: 2026-04-20T22:31:11.834Z
todos: []
