_ulid: 01KQB2R958DK4042TQZB0JFJ2P
slugs:
  - task-foundation-ai-core
title: "Foundation: AI Intelligence & Orchestration"
type: task
spec_ref: "@01KPNWQND5PA8ZVZEEWXQXK7GH"
meta_ref: null
plan_ref: null
status: in_progress
blocked_by: []
depends_on: []
context: []
priority: 3
tags: []
vcs_refs: []
history:
  - author: Johan.P
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-05-09T07:22:27.885Z
        previous: null
    command: task-start
    timestamp: 2026-05-09T07:22:27.885Z
created_at: 2026-04-28T22:18:30.440Z
started_at: 2026-05-09T07:22:27.885Z
todos: []
