_ulid: 01KPNXFJ8J5Y8A07F0XAKGH06H
slugs:
  - task-token-burn-history
title: "Implement: Token Burn History"
type: task
spec_ref: "@01KPNWTTH2GSHV3Q4W2W7F7KV8"
derivation: auto
status: in_progress
blocked_by: []
depends_on:
  - "@task-token-economics-telemetry"
context: []
priority: 3
tags: []
vcs_refs: []
history:
  - author: Johan.P
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-04-20T22:13:24.026Z
        previous: null
    command: task-start
    timestamp: 2026-04-20T22:13:24.027Z
created_at: 2026-04-20T17:02:18.898Z
started_at: 2026-04-20T22:13:24.026Z
todos: []
