_ulid: 01KPNXFJ8J5Y8A07F0XAKGH06H
slugs:
  - task-token-burn-history
title: "Implement: Token Burn History"
type: task
spec_ref: "@01KPNWTTH2GSHV3Q4W2W7F7KV8"
derivation: auto
status: pending_review
blocked_by: []
depends_on:
  - "@task-token-economics-telemetry"
context: []
priority: 3
tags: []
vcs_refs: []
submission_linkage:
  review_url: null
  branch: main
  captured_at: 2026-04-20T22:19:03.624Z
  commit: f0774d5a478bb6f5680a3dd9eec747867cff3ba4
  remote: origin
  remote_url: https://github.com/bobcat88/simple-code-gui
  upstream_ref: refs/heads/main
history:
  - author: Johan.P
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-04-20T22:13:24.026Z
        previous: null
    command: task-start
    timestamp: 2026-04-20T22:13:24.027Z
  - author: Johan.P
    changes:
      status:
        new: pending_review
        previous: in_progress
      submission_linkage:
        new:
          review_url: null
          branch: main
          captured_at: 2026-04-20T22:19:03.624Z
          commit: f0774d5a478bb6f5680a3dd9eec747867cff3ba4
          remote: origin
          remote_url: https://github.com/bobcat88/simple-code-gui
          upstream_ref: refs/heads/main
        previous: null
      submitted_at:
        new: 2026-04-20T22:19:03.630Z
        previous: null
    command: task-submit
    timestamp: 2026-04-20T22:19:03.631Z
created_at: 2026-04-20T17:02:18.898Z
started_at: 2026-04-20T22:13:24.026Z
submitted_at: 2026-04-20T22:19:03.630Z
todos: []
