_ulid: 01KQJ99XRP1QQQA9B8FCGNV4SE
slugs:
  - task-tiled-terminal-layout
title: "Implement: Tiled Terminal Layout"
type: task
spec_ref: "@tiled-layout"
derivation: auto
status: pending_review
blocked_by: []
depends_on: []
context: []
priority: 3
tags: []
vcs_refs: []
submission_linkage:
  review_url: null
  branch: feature/phase-29-swarm-governance
  captured_at: 2026-05-01T17:28:11.507Z
  commit: d8ded809f05180be8594146eed97e185796880f9
  remote: origin
  remote_url: https://github.com/bobcat88/simple-code-gui
  upstream_ref: refs/heads/feature/phase-29-swarm-governance
history:
  - author: Johan.P
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-05-01T17:28:08.846Z
        previous: null
    command: task-start
    timestamp: 2026-05-01T17:28:08.847Z
  - author: Johan.P
    changes:
      status:
        new: pending_review
        previous: in_progress
      submission_linkage:
        new:
          review_url: null
          branch: feature/phase-29-swarm-governance
          captured_at: 2026-05-01T17:28:11.507Z
          commit: d8ded809f05180be8594146eed97e185796880f9
          remote: origin
          remote_url: https://github.com/bobcat88/simple-code-gui
          upstream_ref: refs/heads/feature/phase-29-swarm-governance
        previous: null
      submitted_at:
        new: 2026-05-01T17:28:11.512Z
        previous: null
    command: task-submit
    timestamp: 2026-05-01T17:28:11.512Z
created_at: 2026-05-01T17:27:41.078Z
started_at: 2026-05-01T17:28:08.846Z
submitted_at: 2026-05-01T17:28:11.512Z
todos: []
