_ulid: 01KQJ8KJD2NKX9Z66TG76P1JNV
slugs:
  - task-sidebar-navigation
title: "Foundation: Sidebar Navigation"
type: task
spec_ref: "@01KK67C9AQPXS2BZXTN88KXCNT"
status: completed
blocked_by: []
depends_on: []
context: []
priority: 3
tags:
  - foundation
vcs_refs: []
created_at: 2026-05-01T17:15:09.373Z
started_at: 2026-05-01T17:15:09.373Z
completed_at: 2026-05-01T17:15:09.373Z
todos: []
automation: eligible
