_ulid: 01KQB2RHE1KHQ3C3H1XYGJK5DZ
slugs:
  - task-foundation-terminal
title: "Foundation: Terminal Management"
type: task
spec_ref: "@01KK67BAXYFC28NYYSCWDPARHC"
meta_ref: null
plan_ref: null
status: in_progress
blocked_by: []
depends_on: []
context: []
priority: 3
tags: []
vcs_refs: []
history:
  - author: Johan.P
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-05-09T07:22:41.079Z
        previous: null
    command: task-start
    timestamp: 2026-05-09T07:22:41.079Z
created_at: 2026-04-28T22:18:38.913Z
started_at: 2026-05-09T07:22:41.079Z
todos: []
