_ulid: 01KQB2RFS22ZAQ1C4C0RNT48N0
slugs:
  - task-foundation-tasks
title: "Foundation: Task Lifecycle"
type: task
spec_ref: "@01KK67BEXPK9TT6168Q1FM5PYD"
meta_ref: null
plan_ref: null
status: in_progress
blocked_by: []
depends_on: []
context: []
priority: 3
tags: []
vcs_refs: []
history:
  - author: Johan.P
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-05-09T07:22:37.828Z
        previous: null
    command: task-start
    timestamp: 2026-05-09T07:22:37.829Z
created_at: 2026-04-28T22:18:37.217Z
started_at: 2026-05-09T07:22:37.828Z
todos: []
