_ulid: 01KPNXFSKSCJADKNJGETRD4KG0
slugs:
  - task-project-quick-switcher
title: "Implement: Project Quick-Switcher"
type: task
spec_ref: "@01KPNWYGEC5WX1JKYWJ2WF0YB0"
derivation: auto
status: pending_review
blocked_by: []
depends_on:
  - "@task-advanced-workspace-control"
context: []
priority: 3
tags: []
vcs_refs: []
review_ref: "@01KPRRB1Y266W9ARVWMWGQ5AX9"
submission_linkage:
  review_url: null
  branch: dispatch/task/task-project-quick-switcher/01kpnxfs
  captured_at: 2026-04-21T18:34:18.224Z
  commit: ab30b530ed0693f1519121da53f013f9a9446389
  remote: origin
  remote_url: https://github.com/bobcat88/simple-code-gui
  upstream_ref: refs/heads/dispatch/task/task-project-quick-switcher/01kpnxfs
session_id: 01KPQCTT3CPB8BJVBSA4D3TPW7
history:
  - author: Johan.P
    changes:
      automation:
        new: eligible
        previous: null
    command: task-set
    timestamp: 2026-04-21T06:49:23.275Z
  - author: "@claude"
    changes:
      status:
        new: in_progress
        previous: pending
      session_id:
        new: 01KPQCTT3CPB8BJVBSA4D3TPW7
        previous: null
      started_at:
        new: 2026-04-21T06:50:21.111Z
        previous: null
    command: task-start
    timestamp: 2026-04-21T06:50:21.111Z
  - author: Johan.P
    changes:
      status:
        new: pending_review
        previous: in_progress
      submission_linkage:
        new:
          review_url: null
          branch: dispatch/task/task-project-quick-switcher/01kpnxfs
          captured_at: 2026-04-21T18:34:18.224Z
          commit: ab30b530ed0693f1519121da53f013f9a9446389
          remote: origin
          remote_url: https://github.com/bobcat88/simple-code-gui
          upstream_ref: refs/heads/dispatch/task/task-project-quick-switcher/01kpnxfs
        previous: null
      submitted_at:
        new: 2026-04-21T18:34:18.232Z
        previous: null
    command: task-submit
    timestamp: 2026-04-21T18:34:18.232Z
  - author: Johan.P
    changes:
      review_ref:
        new: "@01KPRRB1Y266W9ARVWMWGQ5AX9"
        previous: null
    command: review-link
    timestamp: 2026-04-21T19:30:11.553Z
created_at: 2026-04-20T17:02:26.425Z
started_at: 2026-04-21T06:50:21.111Z
submitted_at: 2026-04-21T18:34:18.232Z
todos: []
automation: eligible
