_ulid: 01KPNXFSKSCJADKNJGETRD4KG0
slugs:
  - task-project-quick-switcher
title: "Implement: Project Quick-Switcher"
type: task
spec_ref: "@01KPNWYGEC5WX1JKYWJ2WF0YB0"
derivation: auto
status: pending
blocked_by: []
depends_on:
  - "@task-advanced-workspace-control"
context: []
priority: 3
tags: []
vcs_refs: []
history:
  - author: Johan.P
    changes:
      automation:
        new: eligible
        previous: null
    command: task-set
    timestamp: 2026-04-21T06:49:23.275Z
created_at: 2026-04-20T17:02:26.425Z
todos: []
automation: eligible
