_ulid: 01KQB2RKCHEYTGPPCE1N60FG3G
slugs:
  - task-foundation-voice
title: "Foundation: Voice I/O"
type: task
spec_ref: "@01KK67BDK2JJG20G7JD78SPBCA"
meta_ref: null
plan_ref: null
status: in_progress
blocked_by: []
depends_on: []
context: []
priority: 3
tags: []
vcs_refs: []
history:
  - author: Johan.P
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-05-01T17:18:33.125Z
        previous: null
    command: task-start
    timestamp: 2026-05-01T17:18:33.126Z
created_at: 2026-04-28T22:18:40.913Z
started_at: 2026-05-01T17:18:33.125Z
todos: []
