_ulid: 01KQB2RKCHEYTGPPCE1N60FG3G
slugs:
  - task-foundation-voice
title: "Foundation: Voice I/O"
type: task
spec_ref: "@01KK67BDK2JJG20G7JD78SPBCA"
meta_ref: null
plan_ref: null
status: pending_review
blocked_by: []
depends_on: []
context: []
priority: 3
tags: []
vcs_refs: []
submission_linkage:
  review_url: null
  branch: feature/phase-29-swarm-governance
  captured_at: 2026-05-01T17:18:45.868Z
  commit: 14df5b59369422b64317f4d97faef91d2cf4d848
  remote: origin
  remote_url: https://github.com/bobcat88/simple-code-gui
  upstream_ref: refs/heads/feature/phase-29-swarm-governance
history:
  - author: Johan.P
    changes:
      status:
        new: in_progress
        previous: pending
      started_at:
        new: 2026-05-01T17:18:33.125Z
        previous: null
    command: task-start
    timestamp: 2026-05-01T17:18:33.126Z
  - author: Johan.P
    changes:
      status:
        new: pending_review
        previous: in_progress
      submission_linkage:
        new:
          review_url: null
          branch: feature/phase-29-swarm-governance
          captured_at: 2026-05-01T17:18:45.868Z
          commit: 14df5b59369422b64317f4d97faef91d2cf4d848
          remote: origin
          remote_url: https://github.com/bobcat88/simple-code-gui
          upstream_ref: refs/heads/feature/phase-29-swarm-governance
        previous: null
      submitted_at:
        new: 2026-05-01T17:18:45.873Z
        previous: null
    command: task-submit
    timestamp: 2026-05-01T17:18:45.873Z
created_at: 2026-04-28T22:18:40.913Z
started_at: 2026-05-01T17:18:33.125Z
submitted_at: 2026-05-01T17:18:45.873Z
todos: []
